version: "3.8"
services:
  ## MONGO DATABASE FOR USERS
  authdb:
    image: mongo:5.0.25
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - login-data:/data/db

  data:
    image: mongo:5.0.25
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27018:27017"
    volumes:
      - user-data:/data/db

  ### Auth service ###
  auth_service:
    image: jurek01/auth
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb://admin:admin@authdb:27017/users?authSource=admin
    ports:
      - "3001:3000"

  ### User service ###

  user_service:
    image: jurek01/user_service
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb://admin:admin@data:27017/userservice?authSource=admin
    ports:
      - "3002:3000"

  ### User service ###
  expire_service:
    image: jurek01/expire_service
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb://admin:admin@authdb:27017/userservice?authSource=admin
    ports:
      - "3003:3000"

volumes:
  login-data:
    driver: local
  user-data:
    driver: local
