version: "3.8"
services:
  ## MONGO DATABASE FOR USERS
  authdb:
    image: mongo:5.0.25
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - login-data:/data/db

  data:
    image: mongo:5.0.25
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27018:27017"
    volumes:
      - user-data:/data/db

volumes:
  login-data:
    driver: local
  user-data:
    driver: local
